version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: masterkey
      POSTGRES_USER: HR
      POSTGRES_DB: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql